const defineTrack = (model, module, copy) => {
  const [hypothesis, baseline, decision, artifact, test, pass, fail, nextMove] = copy;
  const id = `${model}.${module}`;
  return {
    id,
    model,
    module,
    toolKey: module,
    hypothesis,
    baseline,
    passSignal: pass,
    failSignal: fail,
    nextMove,
    moves: [
      {
        key: "decision",
        kind: "Decision",
        title: "Make the operating decision",
        detail: decision,
        doneWhen: "The choice and the tradeoff it creates are written in one sentence.",
      },
      {
        key: "artifact",
        kind: "Artifact",
        title: "Build the smallest usable asset",
        detail: artifact,
        doneWhen: "A usable version exists outside your notes and is ready for another person.",
      },
      {
        key: "test",
        kind: "Real-world test",
        title: "Put the assumption in contact with reality",
        detail: test,
        doneWhen: pass,
      },
    ],
  };
};

const COPY = {
  creator: {
    leverage: [
      "One strong source idea can create more reach and revenue without requiring a new idea for every channel.",
      "How many hours and original drafts did your last five published pieces require?",
      "Choose one proven source piece and the two formats most likely to extend its useful life.",
      "Create a reusable source-to-derivative template with hooks, excerpts, and one offer path.",
      "Publish two derivatives from the same source piece and compare production time and response with your normal process.",
      "Two useful pieces ship in less time than one normal piece, with at least one audience or commercial signal.",
      "Production time does not fall or the derivatives produce no useful signal.",
      "Keep the best-performing format and turn the template into next month's default workflow.",
    ],
    systems: [
      "A defined publishing rhythm will make output more dependable than relying on inspiration.",
      "How many planned pieces shipped on their intended date during the last four weeks?",
      "Choose one realistic weekly cadence and remove every channel that the cadence cannot support.",
      "Build a one-page publishing workflow covering idea capture, production, review, publishing, and follow-up.",
      "Run one complete piece through the workflow on its scheduled date.",
      "The piece ships on time and every step can be repeated from the written workflow.",
      "The piece misses its date or an essential step still depends on memory.",
      "Fix the step that caused delay, then schedule the next two pieces through the revised workflow.",
    ],
    strategy: [
      "A clearer audience-outcome promise will make content and offers easier to understand and act on.",
      "Of your last ten audience responses, how many came from the same type of person seeking the same result?",
      "Choose one audience, one urgent outcome, and one topic or offer you will stop serving for now.",
      "Write a positioning line and revise one profile, landing page, or offer introduction around it.",
      "Show the revised promise to five target people and ask what they believe it helps them do.",
      "At least three of five describe the intended audience and outcome without coaching.",
      "Fewer than three understand the intended outcome or they describe conflicting audiences.",
      "Keep the promise if it passes; otherwise use their repeated language to write and retest one revision.",
    ],
    building: [
      "A smaller public release will create better information than another private revision.",
      "How many finished pieces, offers, or products reached another person in the last 30 days?",
      "Choose the smallest release that can answer one important audience or purchase question.",
      "Produce the public version with a clear response, signup, or purchase path.",
      "Release it to at least ten relevant people and record what they do, not only what they say.",
      "The release reaches ten relevant people and creates at least two observable responses.",
      "It does not reach ten people or produces no behavior that informs the next version.",
      "Repeat the distribution that created a signal, or revise the promise before adding more scope.",
    ],
    ownership: [
      "A direct audience relationship will make the creator business less dependent on platform distribution.",
      "What percentage of the people you reached last month can you contact directly today?",
      "Choose one reason a follower would willingly move to an email list or owned community.",
      "Create the smallest owned destination and one useful signup asset connected to your current work.",
      "Place the invitation in three relevant platform touchpoints and measure direct signups for seven days.",
      "At least five relevant people move into a channel you control.",
      "The invitation receives attention but fewer than five people choose the owned channel.",
      "Keep the strongest invitation placement, improve the value exchange, and run it for another week.",
    ],
    network: [
      "A specific sharing reason will carry the work farther than repeatedly asking for generic support.",
      "How many verified shares, referrals, or introductions did your work create last month?",
      "Choose one moment when sharing your work helps the audience member express identity or help someone else.",
      "Create one shareable asset with a clear recipient, message, and referral path.",
      "Give it to ten engaged people and ask them to send it to one specific person who needs it.",
      "At least three shares or qualified introductions occur without additional prompting.",
      "Fewer than three people share it or recipients do not match the intended audience.",
      "Keep the sharing reason if it passes; otherwise interview two non-sharers before redesigning the loop.",
    ],
    economy: [
      "Connecting one offer to proven audience demand will improve revenue quality more than adding another unrelated offer.",
      "What did each current offer earn in the last 90 days, and how many hours did each require?",
      "Choose the one offer with the strongest combination of demand, margin, and strategic fit.",
      "Create a simple offer economics sheet and one revised purchase path for that offer.",
      "Present the offer to ten relevant audience members or past buyers and track purchase behavior.",
      "The test produces at least one purchase or three qualified buying conversations at acceptable effort.",
      "No one progresses toward purchase or delivery economics remain unsustainable.",
      "Double down on the proven offer, or revise its audience and outcome before creating anything new.",
    ],
    focus: [
      "One editorial and commercial priority will compound faster than several partially served directions.",
      "How many topics, channels, and offers received meaningful work last week?",
      "Choose one 14-day publishing and revenue priority, then freeze everything that does not support it.",
      "Create a visible two-week release calendar containing only work tied to that priority.",
      "Complete the first three scheduled work sessions and record whether the intended output finished.",
      "All three sessions finish their intended output without reopening a frozen priority.",
      "A frozen priority interrupts the sprint or fewer than two intended outputs finish.",
      "Remove the recurring interruption and protect the same priority for one more week.",
    ],
    forces: [
      "Reducing algorithm-led decisions will make the creator's direction more responsive to owned audience evidence.",
      "How many major content or offer decisions last month came from trends versus direct audience evidence?",
      "Choose one owned evidence source that will outrank platform trends during this sprint.",
      "Build a weekly evidence note containing audience questions, replies, purchases, and repeated language.",
      "Use the evidence note to make one content or offer decision, then compare its response with a trend-led decision.",
      "The evidence-led decision produces a clearer audience or commercial signal than the trend-led comparison.",
      "The evidence is too thin to guide a decision or the response remains indistinguishable.",
      "Collect five more direct audience signals before changing direction again.",
    ],
  },
  service: {
    leverage: [
      "Turning one repeated deliverable into a reusable component will reduce delivery time without reducing client value.",
      "How many hours did the same type of client deliverable consume across your last three projects?",
      "Choose one repeated deliverable to standardize and define what must remain custom.",
      "Build a reusable template, checklist, or client-facing asset for that deliverable.",
      "Use it in one live client or realistic sample workflow and compare time and quality with the previous approach.",
      "The deliverable meets the same standard while requiring at least 20 percent less active time.",
      "Time does not fall or the reusable version reduces client quality.",
      "Standardize the reusable portion and document the boundary where expert judgment still belongs.",
    ],
    systems: [
      "A documented delivery path will reduce founder dependence and make quality more consistent.",
      "How many delivery steps could another person complete today without asking you what happens next?",
      "Choose one recurring client workflow and name its trigger, owner, finish, and quality standard.",
      "Create the operating checklist and the client inputs required before work begins.",
      "Have another person or a fresh version of yourself run the workflow using only the document.",
      "The workflow reaches its finish with no more than one clarification and meets the quality standard.",
      "It requires repeated explanation or misses an essential quality check.",
      "Repair the unclear step and use the workflow as the default on the next client engagement.",
    ],
    strategy: [
      "A narrower service promise will increase qualified inquiries and make sales conversations easier to convert.",
      "Of your last five inquiries, how many shared the same buyer, problem, and desired outcome?",
      "Choose one buyer-problem-outcome combination and one service you will stop leading with.",
      "Rewrite the offer page or proposal opening around that combination and one proof point.",
      "Use the revised language in five qualified outreach or sales conversations.",
      "At least three prospects recognize the problem without explanation and one advances to a concrete next step.",
      "Prospects need extensive explanation or none advances after recognizing the problem.",
      "Keep the position if recognition improves; otherwise narrow the problem using language from the five conversations.",
    ],
    building: [
      "A concrete sales or delivery asset will create more useful market contact than further internal planning.",
      "How many finished offer, proof, or delivery assets reached a prospect or client last month?",
      "Choose the smallest asset that removes one obstacle in the current sales or delivery process.",
      "Build and publish the asset with one clear action for a best-fit prospect or client.",
      "Put it in front of five relevant people during a real sales or delivery interaction.",
      "At least two people use it, respond to it, or move forward because of it.",
      "No one uses it or the asset does not remove the intended obstacle.",
      "Keep it in the workflow if it changes behavior; otherwise rebuild only the unclear section.",
    ],
    ownership: [
      "A direct prospect and client channel will reduce dependence on referrals or marketplaces controlled by others.",
      "What percentage of qualified prospects and clients can you contact directly without an intermediary?",
      "Choose one direct relationship asset to build: an email list, CRM segment, or owned referral network.",
      "Create the capture and follow-up path with a specific reason to stay connected.",
      "Invite ten relevant contacts into the owned relationship and measure opt-in and response.",
      "At least five contacts opt in and at least two respond to the first useful follow-up.",
      "Fewer than five opt in or the follow-up produces no response.",
      "Keep the strongest acquisition source and improve the reason contacts have to remain connected.",
    ],
    network: [
      "A deliberate introduction mechanism will create more qualified service demand than waiting for informal referrals.",
      "How many qualified introductions came from clients or partners during the last 90 days?",
      "Choose one successful client outcome and the exact type of person who should hear about it next.",
      "Create a concise referral note and proof asset a client or partner can send without rewriting it.",
      "Ask five satisfied clients or partners for one specific introduction using the asset.",
      "At least two qualified introductions occur and one becomes a substantive conversation.",
      "No qualified introductions occur or the introduced people do not match the chosen problem.",
      "Repeat with the client segment that referred best, or revise the requested introduction using their feedback.",
    ],
    economy: [
      "A clearer relationship between price, delivery cost, and client value will reveal which service deserves focus.",
      "For your last three projects, what were revenue, active hours, direct costs, and follow-on value?",
      "Choose the service and pricing structure with the healthiest value-to-effort relationship.",
      "Build a one-page service economics sheet and a revised scope or price boundary.",
      "Use the boundary in the next three qualified proposals or renewal conversations.",
      "At least one buyer accepts the new boundary and projected margin improves.",
      "All qualified buyers reject the boundary or delivery economics remain unchanged.",
      "Keep the boundary if accepted; otherwise change scope before discounting price.",
    ],
    focus: [
      "Concentrating on one offer and one pipeline action will produce more momentum than serving every possible request.",
      "How many services, buyer types, and acquisition channels received active effort last week?",
      "Choose one offer and one pipeline action for the sprint, then pause competing offers and channels.",
      "Create a two-week sales and delivery board containing only work tied to that choice.",
      "Complete three scheduled pipeline blocks and track qualified conversations created.",
      "All three blocks happen and produce at least one qualified conversation or clear disqualification evidence.",
      "The blocks are repeatedly displaced or produce no interpretable evidence.",
      "Remove the displacement and repeat the strongest pipeline action for one more week.",
    ],
    forces: [
      "Separating buyer evidence from platform or referral pressure will improve service positioning decisions.",
      "How many recent service decisions came from direct buyer evidence versus competitor or platform behavior?",
      "Choose one buyer evidence source that will govern the next offer decision.",
      "Create an evidence log from calls, proposals, objections, wins, and losses.",
      "Use the log to revise one offer decision and test it in three buyer conversations.",
      "The same buyer language appears in at least two conversations and clarifies the offer decision.",
      "The evidence remains contradictory or does not change the decision.",
      "Gather five more win-loss signals before following another market trend.",
    ],
  },
  community: {
    leverage: [
      "A member-led ritual can create recurring value without requiring the founder to initiate every interaction.",
      "What share of valuable member activity last month began without you?",
      "Choose one recurring member need that a peer, host, or structured ritual can serve.",
      "Build the ritual guide, prompt, schedule, and host instructions.",
      "Run the ritual once with a member host and measure participation and useful exchanges.",
      "The ritual runs without founder intervention and at least three members contribute useful value.",
      "The founder must rescue it or fewer than three members contribute.",
      "Keep and schedule the ritual if it works; otherwise interview the host and simplify one source of friction.",
    ],
    systems: [
      "Consistent onboarding and follow-up will improve participation more than adding more programming.",
      "How many recent members completed onboarding and participated within their first seven days?",
      "Choose the single first-week behavior most associated with an engaged member.",
      "Create a repeatable welcome path that leads every new member toward that behavior.",
      "Run five new or test members through the path and record completion and first participation.",
      "At least four complete onboarding and three perform the chosen first-week behavior.",
      "Fewer than four complete or fewer than three reach the behavior.",
      "Repair the largest onboarding drop-off before adding another community program.",
    ],
    strategy: [
      "A community organized around one recurring member outcome will retain better than one organized around broad belonging alone.",
      "How consistently do active members describe the same practical or emotional outcome?",
      "Choose one recurring member outcome and one audience the community will not optimize for now.",
      "Rewrite the community promise and next event or onboarding message around that outcome.",
      "Ask five active and five inactive members what they believe the community helps them achieve.",
      "At least six of ten independently name the intended outcome or a close equivalent.",
      "Fewer than six name it or active and inactive members describe incompatible value.",
      "Keep the promise if it passes; otherwise rebuild it from the language used by retained members.",
    ],
    building: [
      "One small member-facing experiment will reveal more than planning a full programming calendar.",
      "How many programming or growth experiments reached members last month?",
      "Choose one member behavior or outcome the next experiment must test.",
      "Build the smallest event, prompt, resource, or challenge capable of producing that behavior.",
      "Release it to a defined member segment and measure participation and completion.",
      "At least 20 percent of the invited segment participates and the intended behavior is observable.",
      "Participation is below 20 percent or the behavior cannot be observed.",
      "Repeat with the responding segment, or change the invitation before expanding the program.",
    ],
    ownership: [
      "Owning member identity and contact data will reduce platform risk and improve direct service.",
      "What member contact, participation, and relationship data can you export and use today?",
      "Choose the critical member relationship data that must exist outside the community platform.",
      "Create an owned member directory or CRM structure with consent and a useful reason to participate.",
      "Invite a pilot group to complete or verify their owned member record.",
      "At least 60 percent of the pilot completes the record and can be reached directly.",
      "Most members decline or the record does not improve direct reach.",
      "Keep only the fields members understand and extend the verified structure to the next segment.",
    ],
    network: [
      "A member-to-member value loop will improve participation and acquisition without requiring constant promotion.",
      "How many meaningful introductions, replies, or collaborations occurred between members last month?",
      "Choose one member action that should naturally create value for another member.",
      "Build the prompt, matching rule, or recognition mechanism that makes the action easy and visible.",
      "Run the loop with ten members and track contributions, recipients, and follow-on interaction.",
      "At least four members contribute and at least three recipients respond or continue the interaction.",
      "Fewer than four contribute or interactions stop after the first exchange.",
      "Repeat the loop with the strongest participant segment, or remove the step that blocked contribution.",
    ],
    economy: [
      "A paid promise tied to the community's recurring outcome will improve revenue and retention quality.",
      "What are current revenue per member, delivery cost, renewal rate, and founder hours per month?",
      "Choose the paid promise and member segment with the clearest outcome and healthiest service cost.",
      "Create a one-page membership economics view and one revised renewal or upgrade offer.",
      "Present the offer to ten qualified members or prospects and record purchase or renewal behavior.",
      "At least two purchase, renew, or enter a qualified decision conversation at sustainable cost.",
      "No one progresses or the offer requires unsustainable founder delivery.",
      "Keep the proven promise and remove programming that does not support retention or margin.",
    ],
    focus: [
      "One member outcome and one participation behavior will create more value than a crowded programming calendar.",
      "How many programs, member segments, and growth initiatives received active work last month?",
      "Choose one member outcome and one behavior for the next 14 days; pause unrelated programming.",
      "Create a two-week community calendar showing only the experiences that support that behavior.",
      "Run the calendar and compare participation with the previous two weeks.",
      "The intended behavior increases or becomes more consistent without additional founder hours.",
      "Participation does not improve or founder workload grows materially.",
      "Keep the program that moved behavior and retire or redesign the one that only created activity.",
    ],
    forces: [
      "Member evidence should govern community decisions more than platform engagement incentives.",
      "How many recent programming decisions came from member outcomes versus platform activity metrics?",
      "Choose one member outcome signal that will outrank likes, posts, or raw activity.",
      "Create a weekly evidence note combining retention, participation quality, and direct member language.",
      "Use the note to change one program decision and observe the next member response.",
      "The decision improves the chosen outcome signal or produces a clear learning from members.",
      "Only surface activity changes or the chosen outcome remains unmeasured.",
      "Collect direct evidence from five members before expanding or replacing the program.",
    ],
  },
  product: {
    leverage: [
      "Removing one repeated manual product operation will create capacity without adding headcount.",
      "How many founder or team hours did the same manual product operation consume last week?",
      "Choose one repeated operation to automate, self-serve, or eliminate and define its acceptable failure boundary.",
      "Build the smallest automation, self-serve flow, or operating rule that handles the common case.",
      "Run five real or representative cases through it and compare time, errors, and intervention required.",
      "At least four of five cases complete correctly with 50 percent less active handling time.",
      "More than one case fails materially or active handling time does not fall.",
      "Expand the common case if it passes; otherwise narrow the automation boundary and retest.",
    ],
    systems: [
      "A tighter evidence-to-release loop will improve learning speed more than increasing the feature backlog.",
      "How many user-informed releases shipped in the last 30 days, and how long did each take?",
      "Choose one user problem, one release owner, and one maximum cycle time for the sprint.",
      "Create a release brief with evidence, scope, acceptance criteria, instrumentation, and rollback conditions.",
      "Ship the release to a defined user segment and observe the intended behavior.",
      "The release ships inside the chosen cycle time and produces interpretable usage or customer evidence.",
      "The release misses the cycle or lacks evidence capable of guiding the next decision.",
      "Keep the cycle if it works; otherwise remove the step or scope that delayed learning.",
    ],
    strategy: [
      "A sharper target user and core job will improve activation and retention decisions.",
      "Among recent users, which segment reaches value fastest and returns most often?",
      "Choose one target user, one core job, and one adjacent request the product will not serve during this sprint.",
      "Rewrite the product promise and one activation path around that user and job.",
      "Test the promise and path with five target users, observing comprehension and first-value behavior.",
      "At least four understand the promise and three reach the intended first-value behavior.",
      "Users misunderstand the promise or fewer than three reach first value.",
      "Keep the segment if behavior improves; otherwise revise the core job using observed friction.",
    ],
    building: [
      "A smaller instrumented release will answer the current product question faster than a broader feature build.",
      "How many finished product changes reached target users and produced usable evidence last month?",
      "Choose the smallest release that can test one product assumption and name the behavior it should change.",
      "Build the release with a clear acceptance check and the minimum instrumentation needed to observe it.",
      "Ship it to a defined user segment and observe behavior for a fixed window.",
      "The release reaches the segment and produces enough behavioral evidence to keep, change, or stop.",
      "The release does not reach users or cannot distinguish success from failure.",
      "Scale the winning behavior, or remove the feature and test the next smallest assumption.",
    ],
    ownership: [
      "Direct control of customer identity, access, and core product data will reduce platform and vendor risk.",
      "Which customer relationships, access paths, and critical data could be lost if one platform changed terms?",
      "Choose the single dependency with the highest combination of likelihood and business impact.",
      "Create an ownership plan covering export, fallback access, customer communication, and migration trigger.",
      "Run one export, recovery, or fallback test using representative customer data and access conditions.",
      "The critical data can be exported and restored, and customers can be reached through a channel you control.",
      "Recovery fails, data is incomplete, or customer contact still depends on the same platform.",
      "Fix the failed recovery step before adding another dependency to the product.",
    ],
    network: [
      "A product-native invitation loop can create qualified acquisition as a consequence of user value.",
      "How many new qualified users arrived through an existing user's action last month?",
      "Choose one moment where inviting another person improves the current user's result.",
      "Build the smallest invitation, collaboration, or output-sharing flow around that moment.",
      "Release it to a defined user segment and track invitations, accepted invitations, and retained use.",
      "At least 20 percent of exposed users invite someone and at least 30 percent of invitees reach first value.",
      "Invitation or activation stays below the threshold, or invites attract the wrong user.",
      "Improve the value moment before adding rewards or broader promotion.",
    ],
    economy: [
      "A clearer unit-economic constraint will reveal whether growth, pricing, or retention deserves attention first.",
      "What are current revenue per customer, acquisition cost, gross margin, retention, and support cost?",
      "Choose the one economic variable that most limits sustainable growth and one lever to test.",
      "Create a simple unit-economics model and the smallest pricing, packaging, or cost experiment.",
      "Run the experiment with a defined customer or prospect segment and measure the selected variable.",
      "The selected variable improves without materially damaging activation, retention, or service quality.",
      "The variable does not improve or the tradeoff damages a more important behavior.",
      "Keep the lever if the tradeoff is acceptable; otherwise reverse it and test the next constraint.",
    ],
    focus: [
      "One product question and one release objective will generate more learning than a crowded roadmap.",
      "How many product objectives, features, and acquisition experiments received active work last week?",
      "Choose one product question for the sprint and explicitly pause every roadmap item that cannot answer it.",
      "Create a two-week release board containing only the evidence, build, and test required for that question.",
      "Complete the first three planned work blocks and track whether each ended with its intended output.",
      "All three blocks finish their output and no paused roadmap item re-enters the sprint.",
      "Fewer than two outputs finish or competing roadmap work interrupts the sprint.",
      "Remove the interruption and protect the same product question until evidence resolves it.",
    ],
    forces: [
      "Direct user behavior should govern the roadmap more than competitor announcements or platform incentives.",
      "How many recent roadmap decisions came from user behavior versus competitors, investors, or platform trends?",
      "Choose one user behavior signal that will govern the next product decision.",
      "Create an evidence brief combining behavior, interviews, support signals, and the incentives behind outside pressure.",
      "Use the brief to make one roadmap decision and test it with the affected user segment.",
      "The decision produces interpretable user evidence and can be defended without citing a competitor trend.",
      "The decision still depends on external pressure or produces no interpretable user response.",
      "Collect five more direct user signals before accepting another externally driven roadmap request.",
    ],
  },
};

export const INTERVENTIONS = Object.fromEntries(
  Object.entries(COPY).map(([model, modules]) => [
    model,
    Object.fromEntries(
      Object.entries(modules).map(([module, copy]) => [module, defineTrack(model, module, copy)])
    ),
  ])
);

export function interventionFor(model, module) {
  return INTERVENTIONS[model]?.[module] || INTERVENTIONS.creator[module];
}

export function allInterventionTracks() {
  return Object.values(INTERVENTIONS).flatMap((modules) => Object.values(modules));
}
